### ISSUE TITLE
Implement edit flow of topics

### ISSUE THREAD

**Issue by anandology** [fossunited/community#8]
A topic will have multiple sections. Each section could be of type text, example, problem etc. 

While it is possible implement this in Frappe with child doctypes, editing them is going to be quite painful. The author of the course would like to edit the entire topic in one go, review and make corrections. We need to provide the flexibility that the author needs and multiple sections for frappe to handle each section separately. 

We need to track each section separately because, later we would like to save the code in each section, multiple revisions etc. 

## Proposed Solution

The topic doctype will have a `contents` field of type markdown. It will support annotating different sections using special markup and this will be processed and split into multiple sections on save. The following is an example of typical markup.

    # Drawing shapes

    Let's see how to draw a circle. 

    {{ section type="example" id="shapes-example-1" runtime="python-canvas" }}
    circle(100, 100, 50)
    {{ end }}

    The `circle` function will draw a circle on the canvas and it takes three inputs: `x` and `y`, the coordinates of the center of the circle and `d`, the diameter of the circle.

    {{ section type="problem" id="shapes-problem-1" runtime="python-canvas" }}
    Write a program to draw two circles touching each other. 
    ![](two-circles.png)
    ----
    # Your code here
    # Hint: you need to call the circle function twice
    {{ end }}

The preprocessor will process this and convert this into multiple sections as shown below as YAML:

```
sections:
    - id: section-0001
      type: text
      contents: > 
        # Drawing shapes
        Let's see how to draw a circle. 
    - id: shape-example-1
      type: example
      runtime: python-canvas 
      code: >
        circle(100, 100, 50)
    - id: section-0002
      type: text
      contents: >     
        The `circle` function will draw a circle on the canvas and it takes three inputs: `x` and `y`, the coordinates of the center of the circle and `d`, the diameter of the circle.
   ... 
```
